[package]
name = "gatejumper-payload"
version = "1.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "gatejumper"

[dependencies]
minhook = "0.9"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Security", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_System_Memory", "Win32_System_Environment", "Win32_System_SystemInformation"] }
